import { Download, FileJson, RefreshCcw, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { LoadingState } from "../components/common/LoadingState";
import { PageHeader } from "../components/common/PageHeader";
import { useDataset } from "../features/dataset/DatasetContext";
import { parseImport } from "../features/dataset/validation";
import type { InterviewDataset } from "../models/dataset";

export function SettingsPage() {
  const { dataset, loading, replaceDataset, resetToDefault } = useDataset(); const fileRef = useRef<HTMLInputElement>(null); const [preview, setPreview] = useState<InterviewDataset | null>(null); const [message, setMessage] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  if (loading || !dataset) return <LoadingState />;
  async function chooseFile(file?: File) { if (!file) return; try { setPreview(parseImport(JSON.parse(await file.text()))); setMessage(null); } catch (reason) { setPreview(null); setMessage({ kind: "error", text: reason instanceof Error ? reason.message : "导入失败。" }); } }
  function exportData() { const url = URL.createObjectURL(new Blob([JSON.stringify(dataset, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `qingyun-speak-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage({ kind: "success", text: "备份文件已生成。" }); }
  return <div className="page settings-page"><PageHeader eyebrow="DATA & SETTINGS" title="数据与设置" description="所有内容只保存在当前浏览器。定期导出一份备份，会更安心。" /><div className="settings-grid"><section className="settings-card"><FileJson /><div><span className="eyebrow">CURRENT DATASET</span><h2>{dataset.metadata.name}</h2><p>{dataset.questions.length} 道题 · {dataset.pronunciation.length} 个发音词条</p><small>最近更新：{new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(dataset.metadata.updatedAt))}</small></div></section><section className="settings-card action"><Upload /><div><h2>导入 JSON</h2><p>支持青云研语 Native V1 与旧 Cici 导出。确认前只做预览，不会覆盖数据。</p><input ref={fileRef} name="dataset-file" type="file" accept="application/json,.json" hidden onChange={(e) => void chooseFile(e.target.files?.[0])} /><button className="button secondary" onClick={() => fileRef.current?.click()}>选择 JSON 文件</button></div></section><section className="settings-card action"><Download /><div><h2>导出备份</h2><p>导出当前完整题库、熟练度、收藏和发音词库。</p><button className="button secondary" onClick={exportData}>导出 JSON</button></div></section><section className="settings-card action warning"><RefreshCcw /><div><h2>恢复默认题库</h2><p>会清除当前浏览器中的修改并恢复 142 道 Native V1 默认题目。</p><button className="button danger-button" onClick={() => { if (confirm("恢复默认题库会覆盖当前数据。建议先导出备份。确定继续？")) void resetToDefault(); }}>恢复默认</button></div></section></div>{message && <div className={`notice ${message.kind}`} role={message.kind === "error" ? "alert" : "status"} aria-live="polite">{message.text}</div>}{preview && <section className="import-preview"><span className="eyebrow">IMPORT PREVIEW</span><h2>准备导入「{preview.metadata.name}」</h2><dl><div><dt>题目</dt><dd>{preview.questions.length}</dd></div><div><dt>发音词条</dt><dd>{preview.pronunciation.length}</dd></div><div><dt>数据版本</dt><dd>V{preview.schemaVersion}</dd></div></dl><p>确认后将覆盖当前数据。建议先导出备份。</p><div><button className="button secondary" onClick={() => setPreview(null)}>取消</button><button className="button primary" onClick={() => { replaceDataset(preview); setPreview(null); setMessage({ kind: "success", text: `已导入 ${preview.questions.length} 道题。` }); }}>确认覆盖并导入</button></div></section>}</div>;
}
